version: "2.1"
services:

  rtorrentvpn:      
    image: binhex/arch-rtorrentvpn:rtorrent-ps-1.1.r54.ga787dd9-1-28
    container_name: rtorrentvpn
    restart: always
    cap_add:
      - NET_ADMIN
    ports:
      - %PORTWEBUIRUTORRENT%:9080
    environment:
      - VPN_ENABLED=yes
      - VPN_PROV=airvpn
      - ENABLE_PRIVOXY=no
      - ENABLE_FLOOD=no
      - ENABLE_AUTODL_IRSSI=no
      - ENABLE_RPC2=yes
      - ENABLE_RPC2_AUTH=yes
      - ENABLE_WEBUI_AUTH=yes
      - RPC2_USER=%USER%
      - RPC2_PASS=%PASSWORD%
      - WEBUI_USER=%USER%
      - WEBUI_PASS=%PASSWORD%
      - LAN_NETWORK=%NETWORK%/24
      - VPN_CLIENT=openvpn
      - NAME_SERVERS=208.67.222.222,109.235.51.12,156.154.70.1,8.8.8.8
      - PHP_TZ=Europe/Paris
      - UMASK=000
      - PUID=%UIDGID%
      - PGID=%UIDGID%
    volumes:
      - /home/%USER%/data:/data
      - /opt/docker_apps/rtorrentvpn/config:/config
      - /etc/localtime:/etc/localtime:ro

  prowlarr:
    image: ghcr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=%UIDGID%
      - PGID=%UIDGID%
      - TZ=Europe/London
    volumes:
      - /opt/docker_apps/app_arr/prowlarr/config:/config
    ports:
      - %PORTWEBUIPROWLARR%:9696
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=%UIDGID%
      - PGID=%UIDGID%
      - TZ=Europe/London
    volumes:
      - /opt/docker_apps/app_arr/radarr/config:/config
      - /home/%USER%/data/torrents/films:/movies
    ports:
      - %PORTWEBUIRADARR%:7878
    restart: unless-stopped

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=%UIDGID%
      - PGID=%UIDGID%
      - TZ=Europe/London
    volumes:
      - /opt/docker_apps/app_arr/sonarr/config:/config
      - /home/%USER%/data/torrents/series:/tv
    ports:
      - %PORTWEBUISONARR%:8989
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    environment:
      - PUID=%UIDGID%
      - PGID=%UIDGID%
      - TZ=Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    command: --cleanup --schedule "0 0 2 * * *"
